-- Parsed 114 surahs from quran-data.xml

-- | Complete metadata for all 114 surahs (auto-generated from quran-data.xml)
allSurahs :: [SurahInfo]
allSurahs =
  [ SurahInfo (SurahNumber 1) (SurahName "الفاتحة" "Al-Faatiha" "The Opening") (VerseCount 7) Meccan (RevelationOrder 5) (RukuCount 1)
  , SurahInfo (SurahNumber 2) (SurahName "البقرة" "Al-Baqara" "The Cow") (VerseCount 286) Medinan (RevelationOrder 87) (RukuCount 40)
  , SurahInfo (SurahNumber 3) (SurahName "آل عمران" "Aal-i-Imraan" "The Family of Imraan") (VerseCount 200) Medinan (RevelationOrder 89) (RukuCount 20)
  , SurahInfo (SurahNumber 4) (SurahName "النساء" "An-Nisaa" "The Women") (VerseCount 176) Medinan (RevelationOrder 92) (RukuCount 24)
  , SurahInfo (SurahNumber 5) (SurahName "المائدة" "Al-Maaida" "The Table") (VerseCount 120) Medinan (RevelationOrder 112) (RukuCount 16)
  , SurahInfo (SurahNumber 6) (SurahName "الأنعام" "Al-An'aam" "The Cattle") (VerseCount 165) Meccan (RevelationOrder 55) (RukuCount 20)
  , SurahInfo (SurahNumber 7) (SurahName "الأعراف" "Al-A'raaf" "The Heights") (VerseCount 206) Meccan (RevelationOrder 39) (RukuCount 24)
  , SurahInfo (SurahNumber 8) (SurahName "الأنفال" "Al-Anfaal" "The Spoils of War") (VerseCount 75) Medinan (RevelationOrder 88) (RukuCount 10)
  , SurahInfo (SurahNumber 9) (SurahName "التوبة" "At-Tawba" "The Repentance") (VerseCount 129) Medinan (RevelationOrder 113) (RukuCount 16)
  , SurahInfo (SurahNumber 10) (SurahName "يونس" "Yunus" "Jonas") (VerseCount 109) Meccan (RevelationOrder 51) (RukuCount 11)
  , SurahInfo (SurahNumber 11) (SurahName "هود" "Hud" "Hud") (VerseCount 123) Meccan (RevelationOrder 52) (RukuCount 10)
  , SurahInfo (SurahNumber 12) (SurahName "يوسف" "Yusuf" "Joseph") (VerseCount 111) Meccan (RevelationOrder 53) (RukuCount 12)
  , SurahInfo (SurahNumber 13) (SurahName "الرعد" "Ar-Ra'd" "The Thunder") (VerseCount 43) Medinan (RevelationOrder 96) (RukuCount 6)
  , SurahInfo (SurahNumber 14) (SurahName "ابراهيم" "Ibrahim" "Abraham") (VerseCount 52) Meccan (RevelationOrder 72) (RukuCount 7)
  , SurahInfo (SurahNumber 15) (SurahName "الحجر" "Al-Hijr" "The Rock") (VerseCount 99) Meccan (RevelationOrder 54) (RukuCount 6)
  , SurahInfo (SurahNumber 16) (SurahName "النحل" "An-Nahl" "The Bee") (VerseCount 128) Meccan (RevelationOrder 70) (RukuCount 16)
  , SurahInfo (SurahNumber 17) (SurahName "الإسراء" "Al-Israa" "The Night Journey") (VerseCount 111) Meccan (RevelationOrder 50) (RukuCount 12)
  , SurahInfo (SurahNumber 18) (SurahName "الكهف" "Al-Kahf" "The Cave") (VerseCount 110) Meccan (RevelationOrder 69) (RukuCount 12)
  , SurahInfo (SurahNumber 19) (SurahName "مريم" "Maryam" "Mary") (VerseCount 98) Meccan (RevelationOrder 44) (RukuCount 6)
  , SurahInfo (SurahNumber 20) (SurahName "طه" "Taa-Haa" "Taa-Haa") (VerseCount 135) Meccan (RevelationOrder 45) (RukuCount 8)
  , SurahInfo (SurahNumber 21) (SurahName "الأنبياء" "Al-Anbiyaa" "The Prophets") (VerseCount 112) Meccan (RevelationOrder 73) (RukuCount 7)
  , SurahInfo (SurahNumber 22) (SurahName "الحج" "Al-Hajj" "The Pilgrimage") (VerseCount 78) Medinan (RevelationOrder 103) (RukuCount 10)
  , SurahInfo (SurahNumber 23) (SurahName "المؤمنون" "Al-Muminoon" "The Believers") (VerseCount 118) Meccan (RevelationOrder 74) (RukuCount 6)
  , SurahInfo (SurahNumber 24) (SurahName "النور" "An-Noor" "The Light") (VerseCount 64) Medinan (RevelationOrder 102) (RukuCount 9)
  , SurahInfo (SurahNumber 25) (SurahName "الفرقان" "Al-Furqaan" "The Criterion") (VerseCount 77) Meccan (RevelationOrder 42) (RukuCount 6)
  , SurahInfo (SurahNumber 26) (SurahName "الشعراء" "Ash-Shu'araa" "The Poets") (VerseCount 227) Meccan (RevelationOrder 47) (RukuCount 11)
  , SurahInfo (SurahNumber 27) (SurahName "النمل" "An-Naml" "The Ant") (VerseCount 93) Meccan (RevelationOrder 48) (RukuCount 7)
  , SurahInfo (SurahNumber 28) (SurahName "القصص" "Al-Qasas" "The Stories") (VerseCount 88) Meccan (RevelationOrder 49) (RukuCount 8)
  , SurahInfo (SurahNumber 29) (SurahName "العنكبوت" "Al-Ankaboot" "The Spider") (VerseCount 69) Meccan (RevelationOrder 85) (RukuCount 7)
  , SurahInfo (SurahNumber 30) (SurahName "الروم" "Ar-Room" "The Romans") (VerseCount 60) Meccan (RevelationOrder 84) (RukuCount 6)
  , SurahInfo (SurahNumber 31) (SurahName "لقمان" "Luqman" "Luqman") (VerseCount 34) Meccan (RevelationOrder 57) (RukuCount 3)
  , SurahInfo (SurahNumber 32) (SurahName "السجدة" "As-Sajda" "The Prostration") (VerseCount 30) Meccan (RevelationOrder 75) (RukuCount 3)
  , SurahInfo (SurahNumber 33) (SurahName "الأحزاب" "Al-Ahzaab" "The Clans") (VerseCount 73) Medinan (RevelationOrder 90) (RukuCount 9)
  , SurahInfo (SurahNumber 34) (SurahName "سبإ" "Saba" "Sheba") (VerseCount 54) Meccan (RevelationOrder 58) (RukuCount 6)
  , SurahInfo (SurahNumber 35) (SurahName "فاطر" "Faatir" "The Originator") (VerseCount 45) Meccan (RevelationOrder 43) (RukuCount 5)
  , SurahInfo (SurahNumber 36) (SurahName "يس" "Yaseen" "Yaseen") (VerseCount 83) Meccan (RevelationOrder 41) (RukuCount 5)
  , SurahInfo (SurahNumber 37) (SurahName "الصافات" "As-Saaffaat" "Those drawn up in Ranks") (VerseCount 182) Meccan (RevelationOrder 56) (RukuCount 5)
  , SurahInfo (SurahNumber 38) (SurahName "ص" "Saad" "The letter Saad") (VerseCount 88) Meccan (RevelationOrder 38) (RukuCount 5)
  , SurahInfo (SurahNumber 39) (SurahName "الزمر" "Az-Zumar" "The Groups") (VerseCount 75) Meccan (RevelationOrder 59) (RukuCount 8)
  , SurahInfo (SurahNumber 40) (SurahName "غافر" "Al-Ghaafir" "The Forgiver") (VerseCount 85) Meccan (RevelationOrder 60) (RukuCount 9)
  , SurahInfo (SurahNumber 41) (SurahName "فصلت" "Fussilat" "Explained in detail") (VerseCount 54) Meccan (RevelationOrder 61) (RukuCount 6)
  , SurahInfo (SurahNumber 42) (SurahName "الشورى" "Ash-Shura" "Consultation") (VerseCount 53) Meccan (RevelationOrder 62) (RukuCount 5)
  , SurahInfo (SurahNumber 43) (SurahName "الزخرف" "Az-Zukhruf" "Ornaments of gold") (VerseCount 89) Meccan (RevelationOrder 63) (RukuCount 7)
  , SurahInfo (SurahNumber 44) (SurahName "الدخان" "Ad-Dukhaan" "The Smoke") (VerseCount 59) Meccan (RevelationOrder 64) (RukuCount 3)
  , SurahInfo (SurahNumber 45) (SurahName "الجاثية" "Al-Jaathiya" "Crouching") (VerseCount 37) Meccan (RevelationOrder 65) (RukuCount 4)
  , SurahInfo (SurahNumber 46) (SurahName "الأحقاف" "Al-Ahqaf" "The Dunes") (VerseCount 35) Meccan (RevelationOrder 66) (RukuCount 4)
  , SurahInfo (SurahNumber 47) (SurahName "محمد" "Muhammad" "Muhammad") (VerseCount 38) Medinan (RevelationOrder 95) (RukuCount 4)
  , SurahInfo (SurahNumber 48) (SurahName "الفتح" "Al-Fath" "The Victory") (VerseCount 29) Medinan (RevelationOrder 111) (RukuCount 4)
  , SurahInfo (SurahNumber 49) (SurahName "الحجرات" "Al-Hujuraat" "The Inner Apartments") (VerseCount 18) Medinan (RevelationOrder 106) (RukuCount 2)
  , SurahInfo (SurahNumber 50) (SurahName "ق" "Qaaf" "The letter Qaaf") (VerseCount 45) Meccan (RevelationOrder 34) (RukuCount 3)
  , SurahInfo (SurahNumber 51) (SurahName "الذاريات" "Adh-Dhaariyat" "The Winnowing Winds") (VerseCount 60) Meccan (RevelationOrder 67) (RukuCount 3)
  , SurahInfo (SurahNumber 52) (SurahName "الطور" "At-Tur" "The Mount") (VerseCount 49) Meccan (RevelationOrder 76) (RukuCount 2)
  , SurahInfo (SurahNumber 53) (SurahName "النجم" "An-Najm" "The Star") (VerseCount 62) Meccan (RevelationOrder 23) (RukuCount 3)
  , SurahInfo (SurahNumber 54) (SurahName "القمر" "Al-Qamar" "The Moon") (VerseCount 55) Meccan (RevelationOrder 37) (RukuCount 3)
  , SurahInfo (SurahNumber 55) (SurahName "الرحمن" "Ar-Rahmaan" "The Beneficent") (VerseCount 78) Medinan (RevelationOrder 97) (RukuCount 3)
  , SurahInfo (SurahNumber 56) (SurahName "الواقعة" "Al-Waaqia" "The Inevitable") (VerseCount 96) Meccan (RevelationOrder 46) (RukuCount 3)
  , SurahInfo (SurahNumber 57) (SurahName "الحديد" "Al-Hadid" "The Iron") (VerseCount 29) Medinan (RevelationOrder 94) (RukuCount 4)
  , SurahInfo (SurahNumber 58) (SurahName "المجادلة" "Al-Mujaadila" "The Pleading Woman") (VerseCount 22) Medinan (RevelationOrder 105) (RukuCount 3)
  , SurahInfo (SurahNumber 59) (SurahName "الحشر" "Al-Hashr" "The Exile") (VerseCount 24) Medinan (RevelationOrder 101) (RukuCount 3)
  , SurahInfo (SurahNumber 60) (SurahName "الممتحنة" "Al-Mumtahana" "She that is to be examined") (VerseCount 13) Medinan (RevelationOrder 91) (RukuCount 2)
  , SurahInfo (SurahNumber 61) (SurahName "الصف" "As-Saff" "The Ranks") (VerseCount 14) Medinan (RevelationOrder 109) (RukuCount 2)
  , SurahInfo (SurahNumber 62) (SurahName "الجمعة" "Al-Jumu'a" "Friday") (VerseCount 11) Medinan (RevelationOrder 110) (RukuCount 2)
  , SurahInfo (SurahNumber 63) (SurahName "المنافقون" "Al-Munaafiqoon" "The Hypocrites") (VerseCount 11) Medinan (RevelationOrder 104) (RukuCount 2)
  , SurahInfo (SurahNumber 64) (SurahName "التغابن" "At-Taghaabun" "Mutual Disillusion") (VerseCount 18) Medinan (RevelationOrder 108) (RukuCount 2)
  , SurahInfo (SurahNumber 65) (SurahName "الطلاق" "At-Talaaq" "Divorce") (VerseCount 12) Medinan (RevelationOrder 99) (RukuCount 2)
  , SurahInfo (SurahNumber 66) (SurahName "التحريم" "At-Tahrim" "The Prohibition") (VerseCount 12) Medinan (RevelationOrder 107) (RukuCount 2)
  , SurahInfo (SurahNumber 67) (SurahName "الملك" "Al-Mulk" "The Sovereignty") (VerseCount 30) Meccan (RevelationOrder 77) (RukuCount 2)
  , SurahInfo (SurahNumber 68) (SurahName "القلم" "Al-Qalam" "The Pen") (VerseCount 52) Meccan (RevelationOrder 2) (RukuCount 2)
  , SurahInfo (SurahNumber 69) (SurahName "الحاقة" "Al-Haaqqa" "The Reality") (VerseCount 52) Meccan (RevelationOrder 78) (RukuCount 2)
  , SurahInfo (SurahNumber 70) (SurahName "المعارج" "Al-Ma'aarij" "The Ascending Stairways") (VerseCount 44) Meccan (RevelationOrder 79) (RukuCount 2)
  , SurahInfo (SurahNumber 71) (SurahName "نوح" "Nooh" "Noah") (VerseCount 28) Meccan (RevelationOrder 71) (RukuCount 2)
  , SurahInfo (SurahNumber 72) (SurahName "الجن" "Al-Jinn" "The Jinn") (VerseCount 28) Meccan (RevelationOrder 40) (RukuCount 2)
  , SurahInfo (SurahNumber 73) (SurahName "المزمل" "Al-Muzzammil" "The Enshrouded One") (VerseCount 20) Meccan (RevelationOrder 3) (RukuCount 2)
  , SurahInfo (SurahNumber 74) (SurahName "المدثر" "Al-Muddaththir" "The Cloaked One") (VerseCount 56) Meccan (RevelationOrder 4) (RukuCount 2)
  , SurahInfo (SurahNumber 75) (SurahName "القيامة" "Al-Qiyaama" "The Resurrection") (VerseCount 40) Meccan (RevelationOrder 31) (RukuCount 2)
  , SurahInfo (SurahNumber 76) (SurahName "الانسان" "Al-Insaan" "Man") (VerseCount 31) Medinan (RevelationOrder 98) (RukuCount 2)
  , SurahInfo (SurahNumber 77) (SurahName "المرسلات" "Al-Mursalaat" "The Emissaries") (VerseCount 50) Meccan (RevelationOrder 33) (RukuCount 2)
  , SurahInfo (SurahNumber 78) (SurahName "النبإ" "An-Naba" "The Announcement") (VerseCount 40) Meccan (RevelationOrder 80) (RukuCount 2)
  , SurahInfo (SurahNumber 79) (SurahName "النازعات" "An-Naazi'aat" "Those who drag forth") (VerseCount 46) Meccan (RevelationOrder 81) (RukuCount 2)
  , SurahInfo (SurahNumber 80) (SurahName "عبس" "Abasa" "He frowned") (VerseCount 42) Meccan (RevelationOrder 24) (RukuCount 1)
  , SurahInfo (SurahNumber 81) (SurahName "التكوير" "At-Takwir" "The Overthrowing") (VerseCount 29) Meccan (RevelationOrder 7) (RukuCount 1)
  , SurahInfo (SurahNumber 82) (SurahName "الإنفطار" "Al-Infitaar" "The Cleaving") (VerseCount 19) Meccan (RevelationOrder 82) (RukuCount 1)
  , SurahInfo (SurahNumber 83) (SurahName "المطففين" "Al-Mutaffifin" "Defrauding") (VerseCount 36) Meccan (RevelationOrder 86) (RukuCount 1)
  , SurahInfo (SurahNumber 84) (SurahName "الإنشقاق" "Al-Inshiqaaq" "The Splitting Open") (VerseCount 25) Meccan (RevelationOrder 83) (RukuCount 1)
  , SurahInfo (SurahNumber 85) (SurahName "البروج" "Al-Burooj" "The Constellations") (VerseCount 22) Meccan (RevelationOrder 27) (RukuCount 1)
  , SurahInfo (SurahNumber 86) (SurahName "الطارق" "At-Taariq" "The Morning Star") (VerseCount 17) Meccan (RevelationOrder 36) (RukuCount 1)
  , SurahInfo (SurahNumber 87) (SurahName "الأعلى" "Al-A'laa" "The Most High") (VerseCount 19) Meccan (RevelationOrder 8) (RukuCount 1)
  , SurahInfo (SurahNumber 88) (SurahName "الغاشية" "Al-Ghaashiya" "The Overwhelming") (VerseCount 26) Meccan (RevelationOrder 68) (RukuCount 1)
  , SurahInfo (SurahNumber 89) (SurahName "الفجر" "Al-Fajr" "The Dawn") (VerseCount 30) Meccan (RevelationOrder 10) (RukuCount 1)
  , SurahInfo (SurahNumber 90) (SurahName "البلد" "Al-Balad" "The City") (VerseCount 20) Meccan (RevelationOrder 35) (RukuCount 1)
  , SurahInfo (SurahNumber 91) (SurahName "الشمس" "Ash-Shams" "The Sun") (VerseCount 15) Meccan (RevelationOrder 26) (RukuCount 1)
  , SurahInfo (SurahNumber 92) (SurahName "الليل" "Al-Lail" "The Night") (VerseCount 21) Meccan (RevelationOrder 9) (RukuCount 1)
  , SurahInfo (SurahNumber 93) (SurahName "الضحى" "Ad-Dhuhaa" "The Morning Hours") (VerseCount 11) Meccan (RevelationOrder 11) (RukuCount 1)
  , SurahInfo (SurahNumber 94) (SurahName "الشرح" "Ash-Sharh" "The Consolation") (VerseCount 8) Meccan (RevelationOrder 12) (RukuCount 1)
  , SurahInfo (SurahNumber 95) (SurahName "التين" "At-Tin" "The Fig") (VerseCount 8) Meccan (RevelationOrder 28) (RukuCount 1)
  , SurahInfo (SurahNumber 96) (SurahName "العلق" "Al-Alaq" "The Clot") (VerseCount 19) Meccan (RevelationOrder 1) (RukuCount 1)
  , SurahInfo (SurahNumber 97) (SurahName "القدر" "Al-Qadr" "The Power, Fate") (VerseCount 5) Meccan (RevelationOrder 25) (RukuCount 1)
  , SurahInfo (SurahNumber 98) (SurahName "البينة" "Al-Bayyina" "The Evidence") (VerseCount 8) Medinan (RevelationOrder 100) (RukuCount 1)
  , SurahInfo (SurahNumber 99) (SurahName "الزلزلة" "Az-Zalzala" "The Earthquake") (VerseCount 8) Medinan (RevelationOrder 93) (RukuCount 1)
  , SurahInfo (SurahNumber 100) (SurahName "العاديات" "Al-Aadiyaat" "The Chargers") (VerseCount 11) Meccan (RevelationOrder 14) (RukuCount 1)
  , SurahInfo (SurahNumber 101) (SurahName "القارعة" "Al-Qaari'a" "The Calamity") (VerseCount 11) Meccan (RevelationOrder 30) (RukuCount 1)
  , SurahInfo (SurahNumber 102) (SurahName "التكاثر" "At-Takaathur" "Competition") (VerseCount 8) Meccan (RevelationOrder 16) (RukuCount 1)
  , SurahInfo (SurahNumber 103) (SurahName "العصر" "Al-Asr" "The Declining Day, Epoch") (VerseCount 3) Meccan (RevelationOrder 13) (RukuCount 1)
  , SurahInfo (SurahNumber 104) (SurahName "الهمزة" "Al-Humaza" "The Traducer") (VerseCount 9) Meccan (RevelationOrder 32) (RukuCount 1)
  , SurahInfo (SurahNumber 105) (SurahName "الفيل" "Al-Fil" "The Elephant") (VerseCount 5) Meccan (RevelationOrder 19) (RukuCount 1)
  , SurahInfo (SurahNumber 106) (SurahName "قريش" "Quraish" "Quraysh") (VerseCount 4) Meccan (RevelationOrder 29) (RukuCount 1)
  , SurahInfo (SurahNumber 107) (SurahName "الماعون" "Al-Maa'un" "Almsgiving") (VerseCount 7) Meccan (RevelationOrder 17) (RukuCount 1)
  , SurahInfo (SurahNumber 108) (SurahName "الكوثر" "Al-Kawthar" "Abundance") (VerseCount 3) Meccan (RevelationOrder 15) (RukuCount 1)
  , SurahInfo (SurahNumber 109) (SurahName "الكافرون" "Al-Kaafiroon" "The Disbelievers") (VerseCount 6) Meccan (RevelationOrder 18) (RukuCount 1)
  , SurahInfo (SurahNumber 110) (SurahName "النصر" "An-Nasr" "Divine Support") (VerseCount 3) Medinan (RevelationOrder 114) (RukuCount 1)
  , SurahInfo (SurahNumber 111) (SurahName "المسد" "Al-Masad" "The Palm Fibre") (VerseCount 5) Meccan (RevelationOrder 6) (RukuCount 1)
  , SurahInfo (SurahNumber 112) (SurahName "الإخلاص" "Al-Ikhlaas" "Sincerity") (VerseCount 4) Meccan (RevelationOrder 22) (RukuCount 1)
  , SurahInfo (SurahNumber 113) (SurahName "الفلق" "Al-Falaq" "The Dawn") (VerseCount 5) Meccan (RevelationOrder 20) (RukuCount 1)
  , SurahInfo (SurahNumber 114) (SurahName "الناس" "An-Naas" "Mankind") (VerseCount 6) Meccan (RevelationOrder 21) (RukuCount 1)
  ]
